### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by HangAround47** [futscdav/Chunkmogrify#1]
Hi!

My card is RTX 3090

(chunkmogrify) PS W:\Chunkmogrify-master> python app.py
Projection mode set to w_projection
Gui init: 0.19s
Loading W:/1.png
Number of faces detected: 1
Detection 0: Left: 319 Top: 320 Right: 587 Bottom: 587
Part 0: (335, 374), Part 1: (338, 411) ...
Device cuda:0 requested, but cuda is not available. Using CPU.
Ran out of input
Initializing StyleganProjector
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Creator\miniconda3\envs\chunkmogrify\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Creator\miniconda3\envs\chunkmogrify\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 592, in run_impl
    fn(*args)
  File "app.py", line 573, in steps_
    step()
  File "app.py", line 533, in step
    self.synthesis.synthesize_with_project_step()
  File "W:\Chunkmogrify-master\synthesis.py", line 259, in synthesize_with_project_step
    self._init_projector()
  File "W:\Chunkmogrify-master\synthesis.py", line 426, in _init_projector
    projector = clasz(gan, self.target_image, self.mask_pull(), w_init=init, **kwargs) #  **kwargs
  File "W:\Chunkmogrify-master\stylegan_project.py", line 264, in __init__
    self.device = provider.device
AttributeError: 'NoneType' object has no attribute 'device'

I've tried something like this:

pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html

torch-1.8.1  to  torch-1.10.1

but still the same.

**Comment by futscdav** [comment]
Make sure to install torch with cuda. This error suggests you installed a version which is CPU only. It can be a bit tricky on Windows sometimes, but go to https://pytorch.org/get-started/locally/ and copy the install commands with the right cuda version selected.
